services:
  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['app.command']

  App\Application:
    public: true
    arguments:
      - !tagged_iterator 'app.command'

  App\Command\UserCommand:
    arguments: [ '@App\Service\UserService' ]

  App\Service\UserService:
    arguments:
      - '@App\Repository\Mysql\UserRepository'
      - '@Symfony\Component\Validator\Validator\ValidatorInterface'

  App\Repository\Mysql\UserRepositoryFactory:
    arguments:
      - '%env(DSN_MYSQL)%'

  App\Repository\Mysql\UserRepository:
    factory: [ '@App\Repository\Mysql\UserRepositoryFactory', 'create' ]


  Symfony\Component\Validator\Validator\ValidatorInterface:
    factory: ['@Symfony\Component\Validator\ValidatorBuilder', 'getValidator']

  Symfony\Component\Validator\ValidatorBuilder: ~